management:
  endpoint:
    beans:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:33306/ddd_china_2019_sample
    username: dev
    password: dev
  flyway:
    enabled: true
